package farma_la_carmela.Interface;

import farma_la_carmela.Model.ArticleList;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.event.ListSelectionListener;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario1
 */
public class MainJFrame extends javax.swing.JFrame {
    private ArticleList articulos;
    private MainJPanel panelArticulo;
    private SalePanel panelSale;
    private JTabbedPane panel_administrador;
    private JTabbedPane panel_Inventario;
    private JTabbedPane panel_vendedor;
    
    
    public MainJPanel getPanelArticulo() {
        return panelArticulo;
    }
    public SalePanel getPanelSale() {
        return panelSale;
    }
    public ArticleList getArticulos() {
        return articulos;
    }

    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame(ArticleList a, LinkedList perfiles) {
        this.articulos=a;
        initComponents();
        
        
        panel_administrador=new JTabbedPane();  
        
        panel_Inventario=new JTabbedPane();
        panel_administrador.addTab("INVENTARIO",panel_Inventario);
        
        panel_vendedor=new JTabbedPane();
        
        
        panelArticulo=new MainJPanel();

        this.panelSale=new SalePanel();
        JPanel panelCaja=new JPanel();

        this.panel_Inventario.addTab("Articulos",panelArticulo);
        this.panel_vendedor.addTab("Ventas", panelSale);
        this.panel_vendedor.addTab("Caja", panelCaja);
        Iterator itr=perfiles.iterator();
        while(itr.hasNext()){
            switch((String)itr.next()){
                case "ADMINISTRADOR":
                    this.panel_general.addTab("ADMINISTRADOR",panel_administrador);
                    
                    
                case "VENDEDOR":
                    
                    this.panel_general.addTab("VENDEDOR",panel_vendedor);
                    break;
            }
        }
    
    }
    
    public void setPerfil(String perfil){
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_general = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Farma La Carmela");
        setPreferredSize(new java.awt.Dimension(750, 530));

        panel_general.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_general, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_general)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void controller(ActionListener ctr1,KeyListener ctr2,ListSelectionListener ctr3){
        panelArticulo.controller(ctr1,ctr2,ctr3);
        panelSale.controller(ctr1,ctr2);
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane panel_general;
    // End of variables declaration//GEN-END:variables
}
